# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-28 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospitalsubjectregistration',
            old_name='api_public_key',
            new_name='hospital_user_name',
        ),
        migrations.RemoveField(
            model_name='hospitalsubjectregistration',
            name='api_consumer_key',
        ),
        migrations.RemoveField(
            model_name='hospitalsubjectregistration',
            name='api_private_key',
        ),
        migrations.AlterField(
            model_name='hospitalsubjectregistration',
            name='isactive',
            field=models.NullBooleanField(db_column='isActive'),
        ),
        migrations.AlterField(
            model_name='hospitalsubjectregistration',
            name='isverified',
            field=models.NullBooleanField(db_column='isVerified'),
        ),
    ]
