# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-19 13:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0004_auto_20160919_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DataOfRegistrationOfDevices', models.DateTimeField(blank=True, verbose_name='Date of Reading')),
                ('isSugarMonitoringDevice', models.BooleanField()),
                ('isWorkOutMachineDevice', models.BooleanField()),
                ('isPulseMonitor', models.BooleanField()),
                ('isTemperatureMonitor', models.BooleanField()),
                ('isSleepPatternsMonitor', models.BooleanField()),
                ('RegistrationID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='polling.HospitalSubjectRegistration')),
            ],
        ),
    ]
