# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-19 13:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0005_deviceregister'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceregister',
            name='RegistrationID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='polling.HospitalSubjectDeviceRegistration'),
        ),
        migrations.AlterField(
            model_name='hospitalinsurancesubjectdata',
            name='RegistrationID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='polling.HospitalSubjectDeviceRegistration'),
        ),
    ]
