# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-19 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0006_auto_20160919_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishsubscribecontact',
            name='startcollect',
            field=models.NullBooleanField(db_column='StartCollect'),
        ),
    ]
