# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-19 14:50
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polling', '0007_auto_20160919_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DataOfRegistrationOfDevices', models.DateTimeField(blank=True, verbose_name='Date of Reading')),
                ('isSugarMonitoringDeviceIncluded', models.BooleanField()),
                ('isWorkOutMachineDeviceIncluded', models.BooleanField()),
                ('isPulseMonitorIncluded', models.BooleanField()),
                ('isTemperatureMonitorIncluded', models.BooleanField()),
                ('isSleepPatternsMonitorIncluded', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='HopitalRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_detail', models.TextField(blank=True, null=True)),
                ('hospital_user_name', models.CharField(max_length=222)),
                ('api_token_key', models.CharField(blank=True, max_length=222, null=True)),
                ('isactive', models.NullBooleanField(db_column='isActive')),
                ('isverified', models.NullBooleanField(db_column='isVerified')),
                ('lastupdate', models.DateTimeField(auto_now_add=True, db_column='LastUpdate')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.RenameModel(
            old_name='ContactLogging',
            new_name='APIContactLogging',
        ),
        migrations.RemoveField(
            model_name='deviceregister',
            name='RegistrationID',
        ),
        migrations.RemoveField(
            model_name='hospitalsubjectdeviceregistration',
            name='hospital_name_id',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RenameField(
            model_name='hospitalsubjectregistration',
            old_name='hospital_detail',
            new_name='Patient_History',
        ),
        migrations.RenameField(
            model_name='publishsubscribecontact',
            old_name='datastreamidentifier',
            new_name='Datastreamidentifier',
        ),
        migrations.RenameField(
            model_name='publishsubscribecontact',
            old_name='dateofcreation',
            new_name='Dateofcreation',
        ),
        migrations.RenameField(
            model_name='publishsubscribecontact',
            old_name='documentation',
            new_name='Documentation',
        ),
        migrations.RenameField(
            model_name='publishsubscribecontact',
            old_name='InsuraceOfficeid',
            new_name='InsuraceOffice_id',
        ),
        migrations.RenameField(
            model_name='publishsubscribecontact',
            old_name='intervalofpull',
            new_name='Intervalofpolling',
        ),
        migrations.RenameField(
            model_name='publishsubscribecontact',
            old_name='startcollect',
            new_name='Startcollect',
        ),
        migrations.RemoveField(
            model_name='hospitalsubjectregistration',
            name='api_token_key',
        ),
        migrations.RemoveField(
            model_name='hospitalsubjectregistration',
            name='hospital_user_name',
        ),
        migrations.RemoveField(
            model_name='hospitalsubjectregistration',
            name='isactive',
        ),
        migrations.RemoveField(
            model_name='hospitalsubjectregistration',
            name='isverified',
        ),
        migrations.RemoveField(
            model_name='publishsubscribecontact',
            name='createbyid',
        ),
        migrations.AddField(
            model_name='hospitalsubjectregistration',
            name='subject_detail',
            field=models.TextField(default=datetime.datetime(2016, 9, 19, 14, 50, 5, 863000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospitalsubjectregistration',
            name='subject_insurance_policy_detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publishsubscribecontact',
            name='CreatebyID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hospitalinsurancesubjectdata',
            name='RegistrationID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='polling.HospitalSubjectRegistration'),
        ),
        migrations.AlterField(
            model_name='publishsubscribecontact',
            name='hospital_subject_device_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='polling.HopitalRegistration'),
        ),
        migrations.AlterModelTable(
            name='hospitalsubjectregistration',
            table=None,
        ),
        migrations.AlterModelTable(
            name='insuraceofficeregistration',
            table=None,
        ),
        migrations.AlterModelTable(
            name='insuranceplancategory',
            table=None,
        ),
        migrations.AlterModelTable(
            name='insurancepremiummodelling',
            table=None,
        ),
        migrations.AlterModelTable(
            name='publishsubscribecontact',
            table=None,
        ),
        migrations.AlterModelTable(
            name='sensordevicetype',
            table=None,
        ),
        migrations.DeleteModel(
            name='DeviceRegister',
        ),
        migrations.DeleteModel(
            name='HospitalSubjectDeviceRegistration',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AddField(
            model_name='deviceregistration',
            name='InsuraceOfficeRegistration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='polling.InsuraceOfficeRegistration'),
        ),
        migrations.AddField(
            model_name='deviceregistration',
            name='InsurancePlanTypeID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='polling.Insuranceplancategory'),
        ),
        migrations.AddField(
            model_name='deviceregistration',
            name='RegistrationID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='polling.HospitalSubjectRegistration'),
        ),
        migrations.AddField(
            model_name='hospitalsubjectregistration',
            name='hospital_name_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='polling.HopitalRegistration'),
        ),
    ]
