# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-21 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0009_auto_20160921_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalsubjectregistration',
            name='InsurancePolicyID',
            field=models.CharField(default=b'4196C2123', max_length=400),
        ),
    ]
