# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-22 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0010_auto_20160921_0959'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadiacData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserData', models.TextField(db_column='UserData')),
                ('lastupdate', models.DateTimeField(auto_now_add=True, db_column='LastUpdate')),
            ],
        ),
        migrations.AlterField(
            model_name='hospitalsubjectregistration',
            name='InsurancePolicyID',
            field=models.CharField(default=b'7D798C114', max_length=400),
        ),
    ]
