# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-23 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0011_auto_20160922_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalsubjectregistration',
            name='InsurancePolicyID',
            field=models.CharField(default=b'A89E920C9', max_length=400),
        ),
    ]
